export enum Actions {
  UPDATE_SCOREBOARD = 'UPDATE_SCOREBOARD',
  UPDATE_RECORD_DRAFT = 'UPDATE_RECORD_DRAFT',
  UPDATE_RECORD_QUERY = 'UPDATE_RECORD_QUERY',
  RESET_RECORD_DRAFT = 'RESET_RECORD_DRAFT',
  RESET_SCOREBOARD = 'RESET_SCOREBOARD',
  CAPTURE_READING = 'CAPTURE_READING',
  DELETE_RECORD_DRAFT = 'DELETE_RECORD_DRAFT',
}
